### PR TITLE
timemachines/timemachines/optimizers/requirements.txt

### PR DESCRIPTION
**Pull request by druce**
add requirements.txt for optimizers

includes optimizers that are imported but not currently used by alloptimizers.py, e.g. fbprophet, hyperopt

locally I can install fbprophet with conda install fbprophet but not pip install fbprophet . but probably a local issue and in any event maybe not used

### CODE REVIEW

**Comment by microprediction** [comment]
Aside: I've also had trouble pip installing prophet although upgrading pip and installing pandas first seems to help.

**Comment by druce** [comment]
very cool stuff!

this is my mad science project, so trying a few more optimizers was very
helpful
https://github.com/druce/swr/blob/master/optimize.ipynb

basically the idea is optimize safe withdrawal … write a function that
takes a stock/bond allocation, and a couple of withdrawal rates, evaluates
how it would do historically (or Monte Carlo) using CRRA
certainty equivalent cash flows (real cash flows discounted for
volatility). gives reasonable answers, historically works a little better
than Bengen '4% rule'. i.e. can spend more without running out if you
tolerate a little variability. for simple rules gradient-based Powell or
L-BFGS-B works too. Anyway will blog about it sometime!

will follow your stuff with interest!

**Comment by microprediction** [comment]
Very cool. If you want we could include it as one of the objectives - always looking for real-world objective functions rather than the fake ones.

**Comment by druce** [comment]
thanks Peter! still very much a work in progress but eventually will blog
about and maybe can provide a canonical case/benchmark!

**Pull request merged**
